// Auto-generated by generate-manifest.js — do not edit manually.
// Re-run: node generate-manifest.js
window.MANIFEST = {
  "collections": [
    {
      "id": "Airplanes-Avions~2025",
      "folderName": "Airplanes-Avions~2025",
      "title": {
        "en": "Airplanes",
        "fr": "Avions"
      },
      "date": "2025",
      "description": {
        "en": "A few random photos of aeroplanes.",
        "fr": "Quelques photos en vrac d'avions."
      },
      "covers": [
        "assets/collections/Airplanes-Avions~2025/A320.jpg",
        "assets/collections/Airplanes-Avions~2025/Beluga.jpg",
        "assets/collections/Airplanes-Avions~2025/Sky_in_fire-Ciel_en_feu.jpg"
      ],
      "photos": [
        {
          "filename": "A320.jpg",
          "src": "assets/collections/Airplanes-Avions~2025/A320.jpg",
          "label": {
            "en": "A320",
            "fr": "A320"
          }
        },
        {
          "filename": "Beluga.jpg",
          "src": "assets/collections/Airplanes-Avions~2025/Beluga.jpg",
          "label": {
            "en": "Beluga",
            "fr": "Beluga"
          }
        },
        {
          "filename": "Sky_in_fire-Ciel_en_feu.jpg",
          "src": "assets/collections/Airplanes-Avions~2025/Sky_in_fire-Ciel_en_feu.jpg",
          "label": {
            "en": "Sky in fire",
            "fr": "Ciel en feu"
          }
        }
      ],
      "subcollections": [],
      "allPhotos": [
        {
          "filename": "A320.jpg",
          "src": "assets/collections/Airplanes-Avions~2025/A320.jpg",
          "label": {
            "en": "A320",
            "fr": "A320"
          }
        },
        {
          "filename": "Beluga.jpg",
          "src": "assets/collections/Airplanes-Avions~2025/Beluga.jpg",
          "label": {
            "en": "Beluga",
            "fr": "Beluga"
          }
        },
        {
          "filename": "Sky_in_fire-Ciel_en_feu.jpg",
          "src": "assets/collections/Airplanes-Avions~2025/Sky_in_fire-Ciel_en_feu.jpg",
          "label": {
            "en": "Sky in fire",
            "fr": "Ciel en feu"
          }
        }
      ]
    },
    {
      "id": "Asson_Zoo-Zoo_d'Asson~2024",
      "folderName": "Asson_Zoo-Zoo_d'Asson~2024",
      "title": {
        "en": "Asson Zoo",
        "fr": "Zoo d'Asson"
      },
      "date": "2024",
      "description": {
        "en": "A trip to the zoo with an university association.",
        "fr": "Sortie au zoo avec une association universitaire."
      },
      "covers": [
        "assets/collections/Asson_Zoo-Zoo_d'Asson~2024/Animals-Animaux/Daubenton's_Bittern-Hocco_de_Daubenton.jpg",
        "assets/collections/Asson_Zoo-Zoo_d'Asson~2024/Animals-Animaux/Flamingo-Flamand_rose.jpg",
        "assets/collections/Asson_Zoo-Zoo_d'Asson~2024/Animals-Animaux/Grey_otter-Loutre_cendrée.jpg",
        "assets/collections/Asson_Zoo-Zoo_d'Asson~2024/Animals-Animaux/Nicobar_pigeon-Pigeon_Nicobar.jpg",
        "assets/collections/Asson_Zoo-Zoo_d'Asson~2024/Animals-Animaux/Ocelot.jpg",
        "assets/collections/Asson_Zoo-Zoo_d'Asson~2024/Animals-Animaux/Red_panda-Panda_roux.jpg",
        "assets/collections/Asson_Zoo-Zoo_d'Asson~2024/Animals-Animaux/Serval.jpg",
        "assets/collections/Asson_Zoo-Zoo_d'Asson~2024/Animals-Animaux/Snow_leopard-Panthère_des_neiges.jpg",
        "assets/collections/Asson_Zoo-Zoo_d'Asson~2024/Animals-Animaux/Southern_Bucorve-Bucorve_du_sud.jpg",
        "assets/collections/Asson_Zoo-Zoo_d'Asson~2024/Animals-Animaux/White_cheeked_Gibon-Gibbon_à_favoris_blancs.jpg"
      ],
      "photos": [],
      "subcollections": [
        {
          "id": "Animals-Animaux",
          "title": {
            "en": "Animals",
            "fr": "Animaux"
          },
          "description": null,
          "photos": [
            {
              "filename": "Daubenton's_Bittern-Hocco_de_Daubenton.jpg",
              "src": "assets/collections/Asson_Zoo-Zoo_d'Asson~2024/Animals-Animaux/Daubenton's_Bittern-Hocco_de_Daubenton.jpg",
              "label": {
                "en": "Daubenton's Bittern",
                "fr": "Hocco de Daubenton"
              }
            },
            {
              "filename": "Flamingo-Flamand_rose.jpg",
              "src": "assets/collections/Asson_Zoo-Zoo_d'Asson~2024/Animals-Animaux/Flamingo-Flamand_rose.jpg",
              "label": {
                "en": "Flamingo",
                "fr": "Flamand rose"
              }
            },
            {
              "filename": "Grey_otter-Loutre_cendrée.jpg",
              "src": "assets/collections/Asson_Zoo-Zoo_d'Asson~2024/Animals-Animaux/Grey_otter-Loutre_cendrée.jpg",
              "label": {
                "en": "Grey otter",
                "fr": "Loutre cendrée"
              }
            },
            {
              "filename": "Nicobar_pigeon-Pigeon_Nicobar.jpg",
              "src": "assets/collections/Asson_Zoo-Zoo_d'Asson~2024/Animals-Animaux/Nicobar_pigeon-Pigeon_Nicobar.jpg",
              "label": {
                "en": "Nicobar pigeon",
                "fr": "Pigeon Nicobar"
              }
            },
            {
              "filename": "Ocelot.jpg",
              "src": "assets/collections/Asson_Zoo-Zoo_d'Asson~2024/Animals-Animaux/Ocelot.jpg",
              "label": {
                "en": "Ocelot",
                "fr": "Ocelot"
              }
            },
            {
              "filename": "Red_panda-Panda_roux.jpg",
              "src": "assets/collections/Asson_Zoo-Zoo_d'Asson~2024/Animals-Animaux/Red_panda-Panda_roux.jpg",
              "label": {
                "en": "Red panda",
                "fr": "Panda roux"
              }
            },
            {
              "filename": "Serval.jpg",
              "src": "assets/collections/Asson_Zoo-Zoo_d'Asson~2024/Animals-Animaux/Serval.jpg",
              "label": {
                "en": "Serval",
                "fr": "Serval"
              }
            },
            {
              "filename": "Snow_leopard-Panthère_des_neiges.jpg",
              "src": "assets/collections/Asson_Zoo-Zoo_d'Asson~2024/Animals-Animaux/Snow_leopard-Panthère_des_neiges.jpg",
              "label": {
                "en": "Snow leopard",
                "fr": "Panthère des neiges"
              }
            },
            {
              "filename": "Southern_Bucorve-Bucorve_du_sud.jpg",
              "src": "assets/collections/Asson_Zoo-Zoo_d'Asson~2024/Animals-Animaux/Southern_Bucorve-Bucorve_du_sud.jpg",
              "label": {
                "en": "Southern Bucorve",
                "fr": "Bucorve du sud"
              }
            },
            {
              "filename": "White_cheeked_Gibon-Gibbon_à_favoris_blancs.jpg",
              "src": "assets/collections/Asson_Zoo-Zoo_d'Asson~2024/Animals-Animaux/White_cheeked_Gibon-Gibbon_à_favoris_blancs.jpg",
              "label": {
                "en": "White cheeked Gibon",
                "fr": "Gibbon à favoris blancs"
              }
            }
          ]
        }
      ],
      "allPhotos": [
        {
          "filename": "Daubenton's_Bittern-Hocco_de_Daubenton.jpg",
          "src": "assets/collections/Asson_Zoo-Zoo_d'Asson~2024/Animals-Animaux/Daubenton's_Bittern-Hocco_de_Daubenton.jpg",
          "label": {
            "en": "Daubenton's Bittern",
            "fr": "Hocco de Daubenton"
          }
        },
        {
          "filename": "Flamingo-Flamand_rose.jpg",
          "src": "assets/collections/Asson_Zoo-Zoo_d'Asson~2024/Animals-Animaux/Flamingo-Flamand_rose.jpg",
          "label": {
            "en": "Flamingo",
            "fr": "Flamand rose"
          }
        },
        {
          "filename": "Grey_otter-Loutre_cendrée.jpg",
          "src": "assets/collections/Asson_Zoo-Zoo_d'Asson~2024/Animals-Animaux/Grey_otter-Loutre_cendrée.jpg",
          "label": {
            "en": "Grey otter",
            "fr": "Loutre cendrée"
          }
        },
        {
          "filename": "Nicobar_pigeon-Pigeon_Nicobar.jpg",
          "src": "assets/collections/Asson_Zoo-Zoo_d'Asson~2024/Animals-Animaux/Nicobar_pigeon-Pigeon_Nicobar.jpg",
          "label": {
            "en": "Nicobar pigeon",
            "fr": "Pigeon Nicobar"
          }
        },
        {
          "filename": "Ocelot.jpg",
          "src": "assets/collections/Asson_Zoo-Zoo_d'Asson~2024/Animals-Animaux/Ocelot.jpg",
          "label": {
            "en": "Ocelot",
            "fr": "Ocelot"
          }
        },
        {
          "filename": "Red_panda-Panda_roux.jpg",
          "src": "assets/collections/Asson_Zoo-Zoo_d'Asson~2024/Animals-Animaux/Red_panda-Panda_roux.jpg",
          "label": {
            "en": "Red panda",
            "fr": "Panda roux"
          }
        },
        {
          "filename": "Serval.jpg",
          "src": "assets/collections/Asson_Zoo-Zoo_d'Asson~2024/Animals-Animaux/Serval.jpg",
          "label": {
            "en": "Serval",
            "fr": "Serval"
          }
        },
        {
          "filename": "Snow_leopard-Panthère_des_neiges.jpg",
          "src": "assets/collections/Asson_Zoo-Zoo_d'Asson~2024/Animals-Animaux/Snow_leopard-Panthère_des_neiges.jpg",
          "label": {
            "en": "Snow leopard",
            "fr": "Panthère des neiges"
          }
        },
        {
          "filename": "Southern_Bucorve-Bucorve_du_sud.jpg",
          "src": "assets/collections/Asson_Zoo-Zoo_d'Asson~2024/Animals-Animaux/Southern_Bucorve-Bucorve_du_sud.jpg",
          "label": {
            "en": "Southern Bucorve",
            "fr": "Bucorve du sud"
          }
        },
        {
          "filename": "White_cheeked_Gibon-Gibbon_à_favoris_blancs.jpg",
          "src": "assets/collections/Asson_Zoo-Zoo_d'Asson~2024/Animals-Animaux/White_cheeked_Gibon-Gibbon_à_favoris_blancs.jpg",
          "label": {
            "en": "White cheeked Gibon",
            "fr": "Gibbon à favoris blancs"
          }
        }
      ]
    },
    {
      "id": "Barèges~2025",
      "folderName": "Barèges~2025",
      "title": {
        "en": "Barèges",
        "fr": "Barèges"
      },
      "date": "2025",
      "description": {
        "en": "Mountain holidays in Barèges, France.",
        "fr": "Vacances à la montagne à Barèges en France."
      },
      "covers": [
        "assets/collections/Barèges~2025/Dog_with_different_colored_eyes-Chien_aux_yeux_vairons.jpg",
        "assets/collections/Barèges~2025/Dog_with_different_colored_eyes_2-Chien_aux_yeux_vairons_2.jpg",
        "assets/collections/Barèges~2025/Red_flowers-Fleurs_rouges.jpg",
        "assets/collections/Barèges~2025/Sheep-Mouton.jpg",
        "assets/collections/Barèges~2025/Sheep_facing_me-Mouton_face_à_moi.jpg",
        "assets/collections/Barèges~2025/Sheeps-Moutons.jpg",
        "assets/collections/Barèges~2025/Sunny_moment_in_life-Moment_de_vie_ensoleillé.jpg"
      ],
      "photos": [
        {
          "filename": "Dog_with_different_colored_eyes-Chien_aux_yeux_vairons.jpg",
          "src": "assets/collections/Barèges~2025/Dog_with_different_colored_eyes-Chien_aux_yeux_vairons.jpg",
          "label": {
            "en": "Dog with different colored eyes",
            "fr": "Chien aux yeux vairons"
          }
        },
        {
          "filename": "Dog_with_different_colored_eyes_2-Chien_aux_yeux_vairons_2.jpg",
          "src": "assets/collections/Barèges~2025/Dog_with_different_colored_eyes_2-Chien_aux_yeux_vairons_2.jpg",
          "label": {
            "en": "Dog with different colored eyes 2",
            "fr": "Chien aux yeux vairons 2"
          }
        },
        {
          "filename": "Red_flowers-Fleurs_rouges.jpg",
          "src": "assets/collections/Barèges~2025/Red_flowers-Fleurs_rouges.jpg",
          "label": {
            "en": "Red flowers",
            "fr": "Fleurs rouges"
          }
        },
        {
          "filename": "Sheep-Mouton.jpg",
          "src": "assets/collections/Barèges~2025/Sheep-Mouton.jpg",
          "label": {
            "en": "Sheep",
            "fr": "Mouton"
          }
        },
        {
          "filename": "Sheep_facing_me-Mouton_face_à_moi.jpg",
          "src": "assets/collections/Barèges~2025/Sheep_facing_me-Mouton_face_à_moi.jpg",
          "label": {
            "en": "Sheep facing me",
            "fr": "Mouton face à moi"
          }
        },
        {
          "filename": "Sheeps-Moutons.jpg",
          "src": "assets/collections/Barèges~2025/Sheeps-Moutons.jpg",
          "label": {
            "en": "Sheeps",
            "fr": "Moutons"
          }
        },
        {
          "filename": "Sunny_moment_in_life-Moment_de_vie_ensoleillé.jpg",
          "src": "assets/collections/Barèges~2025/Sunny_moment_in_life-Moment_de_vie_ensoleillé.jpg",
          "label": {
            "en": "Sunny moment in life",
            "fr": "Moment de vie ensoleillé"
          }
        }
      ],
      "subcollections": [],
      "allPhotos": [
        {
          "filename": "Dog_with_different_colored_eyes-Chien_aux_yeux_vairons.jpg",
          "src": "assets/collections/Barèges~2025/Dog_with_different_colored_eyes-Chien_aux_yeux_vairons.jpg",
          "label": {
            "en": "Dog with different colored eyes",
            "fr": "Chien aux yeux vairons"
          }
        },
        {
          "filename": "Dog_with_different_colored_eyes_2-Chien_aux_yeux_vairons_2.jpg",
          "src": "assets/collections/Barèges~2025/Dog_with_different_colored_eyes_2-Chien_aux_yeux_vairons_2.jpg",
          "label": {
            "en": "Dog with different colored eyes 2",
            "fr": "Chien aux yeux vairons 2"
          }
        },
        {
          "filename": "Red_flowers-Fleurs_rouges.jpg",
          "src": "assets/collections/Barèges~2025/Red_flowers-Fleurs_rouges.jpg",
          "label": {
            "en": "Red flowers",
            "fr": "Fleurs rouges"
          }
        },
        {
          "filename": "Sheep-Mouton.jpg",
          "src": "assets/collections/Barèges~2025/Sheep-Mouton.jpg",
          "label": {
            "en": "Sheep",
            "fr": "Mouton"
          }
        },
        {
          "filename": "Sheep_facing_me-Mouton_face_à_moi.jpg",
          "src": "assets/collections/Barèges~2025/Sheep_facing_me-Mouton_face_à_moi.jpg",
          "label": {
            "en": "Sheep facing me",
            "fr": "Mouton face à moi"
          }
        },
        {
          "filename": "Sheeps-Moutons.jpg",
          "src": "assets/collections/Barèges~2025/Sheeps-Moutons.jpg",
          "label": {
            "en": "Sheeps",
            "fr": "Moutons"
          }
        },
        {
          "filename": "Sunny_moment_in_life-Moment_de_vie_ensoleillé.jpg",
          "src": "assets/collections/Barèges~2025/Sunny_moment_in_life-Moment_de_vie_ensoleillé.jpg",
          "label": {
            "en": "Sunny moment in life",
            "fr": "Moment de vie ensoleillé"
          }
        }
      ]
    },
    {
      "id": "Biarritz~2025",
      "folderName": "Biarritz~2025",
      "title": {
        "en": "Biarritz",
        "fr": "Biarritz"
      },
      "date": "2025",
      "description": {
        "en": "Vacation in Biarritz with friends.",
        "fr": "Vacances à Biarritz entre amis."
      },
      "covers": [
        "assets/collections/Biarritz~2025/Aquarium/Clownfish-Poisson_clown.jpg",
        "assets/collections/Biarritz~2025/Aquarium/Colorful_Jellyfish-Méduses_colorées.jpg",
        "assets/collections/Biarritz~2025/Aquarium/Digitiform_Coral-Corail_digitiforme.jpg",
        "assets/collections/Biarritz~2025/Aquarium/Jellyfish-Méduse.jpg",
        "assets/collections/Biarritz~2025/Aquarium/Longfin_Bannerfish-Poisson_Cocher_commun.jpg",
        "assets/collections/Biarritz~2025/Aquarium/Longhorn_Cowfish-Poisson_vache_à_longues_cornes.jpg",
        "assets/collections/Biarritz~2025/Aquarium/Sea_Turtle-Tortue_de_mer.jpg",
        "assets/collections/Biarritz~2025/Aquarium/Yellow_and_blueback_Fusilier-Fusilier_à_dos_jaune_et_bleu.jpg",
        "assets/collections/Biarritz~2025/Aquarium/Yellow_coral_Goby-Gobie_corail_jaune.jpg",
        "assets/collections/Biarritz~2025/Aquarium/Yellowbanded_Sweetlips-Gaterin_à_bandes_jaunes.jpg",
        "assets/collections/Biarritz~2025/Walk_in_the_city-Balade_en_ville/Meal_at_the_harbor-Repas_sur_le_port.jpg",
        "assets/collections/Biarritz~2025/Walk_in_the_city-Balade_en_ville/Rocher_de_la_Vierge.jpg",
        "assets/collections/Biarritz~2025/Walk_in_the_city-Balade_en_ville/Saint_Eugenie_Church-Église_Saint_Eugénie.jpg",
        "assets/collections/Biarritz~2025/Walk_in_the_city-Balade_en_ville/The_marine_arc-L'arche_marine.jpg",
        "assets/collections/Biarritz~2025/Walk_in_the_city-Balade_en_ville/Villa_Belza.jpg",
        "assets/collections/Biarritz~2025/Walk_in_the_city-Balade_en_ville/Villa_Belza_2.jpg",
        "assets/collections/Biarritz~2025/Walk_in_the_city-Balade_en_ville/Villa_le_Goéland.jpg",
        "assets/collections/Biarritz~2025/Walk_in_the_city-Balade_en_ville/Villa_le_Goéland_2.jpg"
      ],
      "photos": [],
      "subcollections": [
        {
          "id": "Aquarium",
          "title": {
            "en": "Aquarium",
            "fr": "Aquarium"
          },
          "description": null,
          "photos": [
            {
              "filename": "Clownfish-Poisson_clown.jpg",
              "src": "assets/collections/Biarritz~2025/Aquarium/Clownfish-Poisson_clown.jpg",
              "label": {
                "en": "Clownfish",
                "fr": "Poisson clown"
              }
            },
            {
              "filename": "Colorful_Jellyfish-Méduses_colorées.jpg",
              "src": "assets/collections/Biarritz~2025/Aquarium/Colorful_Jellyfish-Méduses_colorées.jpg",
              "label": {
                "en": "Colorful Jellyfish",
                "fr": "Méduses colorées"
              }
            },
            {
              "filename": "Digitiform_Coral-Corail_digitiforme.jpg",
              "src": "assets/collections/Biarritz~2025/Aquarium/Digitiform_Coral-Corail_digitiforme.jpg",
              "label": {
                "en": "Digitiform Coral",
                "fr": "Corail digitiforme"
              }
            },
            {
              "filename": "Jellyfish-Méduse.jpg",
              "src": "assets/collections/Biarritz~2025/Aquarium/Jellyfish-Méduse.jpg",
              "label": {
                "en": "Jellyfish",
                "fr": "Méduse"
              }
            },
            {
              "filename": "Longfin_Bannerfish-Poisson_Cocher_commun.jpg",
              "src": "assets/collections/Biarritz~2025/Aquarium/Longfin_Bannerfish-Poisson_Cocher_commun.jpg",
              "label": {
                "en": "Longfin Bannerfish",
                "fr": "Poisson Cocher commun"
              }
            },
            {
              "filename": "Longhorn_Cowfish-Poisson_vache_à_longues_cornes.jpg",
              "src": "assets/collections/Biarritz~2025/Aquarium/Longhorn_Cowfish-Poisson_vache_à_longues_cornes.jpg",
              "label": {
                "en": "Longhorn Cowfish",
                "fr": "Poisson vache à longues cornes"
              }
            },
            {
              "filename": "Sea_Turtle-Tortue_de_mer.jpg",
              "src": "assets/collections/Biarritz~2025/Aquarium/Sea_Turtle-Tortue_de_mer.jpg",
              "label": {
                "en": "Sea Turtle",
                "fr": "Tortue de mer"
              }
            },
            {
              "filename": "Yellow_and_blueback_Fusilier-Fusilier_à_dos_jaune_et_bleu.jpg",
              "src": "assets/collections/Biarritz~2025/Aquarium/Yellow_and_blueback_Fusilier-Fusilier_à_dos_jaune_et_bleu.jpg",
              "label": {
                "en": "Yellow and blueback Fusilier",
                "fr": "Fusilier à dos jaune et bleu"
              }
            },
            {
              "filename": "Yellow_coral_Goby-Gobie_corail_jaune.jpg",
              "src": "assets/collections/Biarritz~2025/Aquarium/Yellow_coral_Goby-Gobie_corail_jaune.jpg",
              "label": {
                "en": "Yellow coral Goby",
                "fr": "Gobie corail jaune"
              }
            },
            {
              "filename": "Yellowbanded_Sweetlips-Gaterin_à_bandes_jaunes.jpg",
              "src": "assets/collections/Biarritz~2025/Aquarium/Yellowbanded_Sweetlips-Gaterin_à_bandes_jaunes.jpg",
              "label": {
                "en": "Yellowbanded Sweetlips",
                "fr": "Gaterin à bandes jaunes"
              }
            }
          ]
        },
        {
          "id": "Walk_in_the_city-Balade_en_ville",
          "title": {
            "en": "Walk in the city",
            "fr": "Balade en ville"
          },
          "description": null,
          "photos": [
            {
              "filename": "Meal_at_the_harbor-Repas_sur_le_port.jpg",
              "src": "assets/collections/Biarritz~2025/Walk_in_the_city-Balade_en_ville/Meal_at_the_harbor-Repas_sur_le_port.jpg",
              "label": {
                "en": "Meal at the harbor",
                "fr": "Repas sur le port"
              }
            },
            {
              "filename": "Rocher_de_la_Vierge.jpg",
              "src": "assets/collections/Biarritz~2025/Walk_in_the_city-Balade_en_ville/Rocher_de_la_Vierge.jpg",
              "label": {
                "en": "Rocher de la Vierge",
                "fr": "Rocher de la Vierge"
              }
            },
            {
              "filename": "Saint_Eugenie_Church-Église_Saint_Eugénie.jpg",
              "src": "assets/collections/Biarritz~2025/Walk_in_the_city-Balade_en_ville/Saint_Eugenie_Church-Église_Saint_Eugénie.jpg",
              "label": {
                "en": "Saint Eugenie Church",
                "fr": "Église Saint Eugénie"
              }
            },
            {
              "filename": "The_marine_arc-L'arche_marine.jpg",
              "src": "assets/collections/Biarritz~2025/Walk_in_the_city-Balade_en_ville/The_marine_arc-L'arche_marine.jpg",
              "label": {
                "en": "The marine arc",
                "fr": "L'arche marine"
              }
            },
            {
              "filename": "Villa_Belza.jpg",
              "src": "assets/collections/Biarritz~2025/Walk_in_the_city-Balade_en_ville/Villa_Belza.jpg",
              "label": {
                "en": "Villa Belza",
                "fr": "Villa Belza"
              }
            },
            {
              "filename": "Villa_Belza_2.jpg",
              "src": "assets/collections/Biarritz~2025/Walk_in_the_city-Balade_en_ville/Villa_Belza_2.jpg",
              "label": {
                "en": "Villa Belza 2",
                "fr": "Villa Belza 2"
              }
            },
            {
              "filename": "Villa_le_Goéland.jpg",
              "src": "assets/collections/Biarritz~2025/Walk_in_the_city-Balade_en_ville/Villa_le_Goéland.jpg",
              "label": {
                "en": "Villa le Goéland",
                "fr": "Villa le Goéland"
              }
            },
            {
              "filename": "Villa_le_Goéland_2.jpg",
              "src": "assets/collections/Biarritz~2025/Walk_in_the_city-Balade_en_ville/Villa_le_Goéland_2.jpg",
              "label": {
                "en": "Villa le Goéland 2",
                "fr": "Villa le Goéland 2"
              }
            }
          ]
        }
      ],
      "allPhotos": [
        {
          "filename": "Clownfish-Poisson_clown.jpg",
          "src": "assets/collections/Biarritz~2025/Aquarium/Clownfish-Poisson_clown.jpg",
          "label": {
            "en": "Clownfish",
            "fr": "Poisson clown"
          }
        },
        {
          "filename": "Colorful_Jellyfish-Méduses_colorées.jpg",
          "src": "assets/collections/Biarritz~2025/Aquarium/Colorful_Jellyfish-Méduses_colorées.jpg",
          "label": {
            "en": "Colorful Jellyfish",
            "fr": "Méduses colorées"
          }
        },
        {
          "filename": "Digitiform_Coral-Corail_digitiforme.jpg",
          "src": "assets/collections/Biarritz~2025/Aquarium/Digitiform_Coral-Corail_digitiforme.jpg",
          "label": {
            "en": "Digitiform Coral",
            "fr": "Corail digitiforme"
          }
        },
        {
          "filename": "Jellyfish-Méduse.jpg",
          "src": "assets/collections/Biarritz~2025/Aquarium/Jellyfish-Méduse.jpg",
          "label": {
            "en": "Jellyfish",
            "fr": "Méduse"
          }
        },
        {
          "filename": "Longfin_Bannerfish-Poisson_Cocher_commun.jpg",
          "src": "assets/collections/Biarritz~2025/Aquarium/Longfin_Bannerfish-Poisson_Cocher_commun.jpg",
          "label": {
            "en": "Longfin Bannerfish",
            "fr": "Poisson Cocher commun"
          }
        },
        {
          "filename": "Longhorn_Cowfish-Poisson_vache_à_longues_cornes.jpg",
          "src": "assets/collections/Biarritz~2025/Aquarium/Longhorn_Cowfish-Poisson_vache_à_longues_cornes.jpg",
          "label": {
            "en": "Longhorn Cowfish",
            "fr": "Poisson vache à longues cornes"
          }
        },
        {
          "filename": "Sea_Turtle-Tortue_de_mer.jpg",
          "src": "assets/collections/Biarritz~2025/Aquarium/Sea_Turtle-Tortue_de_mer.jpg",
          "label": {
            "en": "Sea Turtle",
            "fr": "Tortue de mer"
          }
        },
        {
          "filename": "Yellow_and_blueback_Fusilier-Fusilier_à_dos_jaune_et_bleu.jpg",
          "src": "assets/collections/Biarritz~2025/Aquarium/Yellow_and_blueback_Fusilier-Fusilier_à_dos_jaune_et_bleu.jpg",
          "label": {
            "en": "Yellow and blueback Fusilier",
            "fr": "Fusilier à dos jaune et bleu"
          }
        },
        {
          "filename": "Yellow_coral_Goby-Gobie_corail_jaune.jpg",
          "src": "assets/collections/Biarritz~2025/Aquarium/Yellow_coral_Goby-Gobie_corail_jaune.jpg",
          "label": {
            "en": "Yellow coral Goby",
            "fr": "Gobie corail jaune"
          }
        },
        {
          "filename": "Yellowbanded_Sweetlips-Gaterin_à_bandes_jaunes.jpg",
          "src": "assets/collections/Biarritz~2025/Aquarium/Yellowbanded_Sweetlips-Gaterin_à_bandes_jaunes.jpg",
          "label": {
            "en": "Yellowbanded Sweetlips",
            "fr": "Gaterin à bandes jaunes"
          }
        },
        {
          "filename": "Meal_at_the_harbor-Repas_sur_le_port.jpg",
          "src": "assets/collections/Biarritz~2025/Walk_in_the_city-Balade_en_ville/Meal_at_the_harbor-Repas_sur_le_port.jpg",
          "label": {
            "en": "Meal at the harbor",
            "fr": "Repas sur le port"
          }
        },
        {
          "filename": "Rocher_de_la_Vierge.jpg",
          "src": "assets/collections/Biarritz~2025/Walk_in_the_city-Balade_en_ville/Rocher_de_la_Vierge.jpg",
          "label": {
            "en": "Rocher de la Vierge",
            "fr": "Rocher de la Vierge"
          }
        },
        {
          "filename": "Saint_Eugenie_Church-Église_Saint_Eugénie.jpg",
          "src": "assets/collections/Biarritz~2025/Walk_in_the_city-Balade_en_ville/Saint_Eugenie_Church-Église_Saint_Eugénie.jpg",
          "label": {
            "en": "Saint Eugenie Church",
            "fr": "Église Saint Eugénie"
          }
        },
        {
          "filename": "The_marine_arc-L'arche_marine.jpg",
          "src": "assets/collections/Biarritz~2025/Walk_in_the_city-Balade_en_ville/The_marine_arc-L'arche_marine.jpg",
          "label": {
            "en": "The marine arc",
            "fr": "L'arche marine"
          }
        },
        {
          "filename": "Villa_Belza.jpg",
          "src": "assets/collections/Biarritz~2025/Walk_in_the_city-Balade_en_ville/Villa_Belza.jpg",
          "label": {
            "en": "Villa Belza",
            "fr": "Villa Belza"
          }
        },
        {
          "filename": "Villa_Belza_2.jpg",
          "src": "assets/collections/Biarritz~2025/Walk_in_the_city-Balade_en_ville/Villa_Belza_2.jpg",
          "label": {
            "en": "Villa Belza 2",
            "fr": "Villa Belza 2"
          }
        },
        {
          "filename": "Villa_le_Goéland.jpg",
          "src": "assets/collections/Biarritz~2025/Walk_in_the_city-Balade_en_ville/Villa_le_Goéland.jpg",
          "label": {
            "en": "Villa le Goéland",
            "fr": "Villa le Goéland"
          }
        },
        {
          "filename": "Villa_le_Goéland_2.jpg",
          "src": "assets/collections/Biarritz~2025/Walk_in_the_city-Balade_en_ville/Villa_le_Goéland_2.jpg",
          "label": {
            "en": "Villa le Goéland 2",
            "fr": "Villa le Goéland 2"
          }
        }
      ]
    },
    {
      "id": "Moon~2025",
      "folderName": "Moon~2025",
      "title": {
        "en": "Moon",
        "fr": "Moon"
      },
      "date": "2025",
      "description": {
        "en": "A few random photos of the Moon.",
        "fr": "Quelques photos en vrac de la Lune."
      },
      "covers": [
        "assets/collections/Moon~2025/Third_Quarter-Dernier_quartier.jpg",
        "assets/collections/Moon~2025/Waxing_Gibbous-Lune_Gibbeuse.jpg"
      ],
      "photos": [
        {
          "filename": "Third_Quarter-Dernier_quartier.jpg",
          "src": "assets/collections/Moon~2025/Third_Quarter-Dernier_quartier.jpg",
          "label": {
            "en": "Third Quarter",
            "fr": "Dernier quartier"
          }
        },
        {
          "filename": "Waxing_Gibbous-Lune_Gibbeuse.jpg",
          "src": "assets/collections/Moon~2025/Waxing_Gibbous-Lune_Gibbeuse.jpg",
          "label": {
            "en": "Waxing Gibbous",
            "fr": "Lune Gibbeuse"
          }
        }
      ],
      "subcollections": [],
      "allPhotos": [
        {
          "filename": "Third_Quarter-Dernier_quartier.jpg",
          "src": "assets/collections/Moon~2025/Third_Quarter-Dernier_quartier.jpg",
          "label": {
            "en": "Third Quarter",
            "fr": "Dernier quartier"
          }
        },
        {
          "filename": "Waxing_Gibbous-Lune_Gibbeuse.jpg",
          "src": "assets/collections/Moon~2025/Waxing_Gibbous-Lune_Gibbeuse.jpg",
          "label": {
            "en": "Waxing Gibbous",
            "fr": "Lune Gibbeuse"
          }
        }
      ]
    },
    {
      "id": "Paris~2024",
      "folderName": "Paris~2024",
      "title": {
        "en": "Paris",
        "fr": "Paris"
      },
      "date": "2024",
      "description": {
        "en": "A stroll through Paris during a short stay.",
        "fr": "Balade dans Paris lors d'un court séjour."
      },
      "covers": [
        "assets/collections/Paris~2024/Galeries Lafayettes.jpg",
        "assets/collections/Paris~2024/Hôtel_des_Invalides_through_the_gate-Hôtel_des_Invalides_à_travers_la_grille.jpg",
        "assets/collections/Paris~2024/Metro.jpg",
        "assets/collections/Paris~2024/Eiffel_Tower/At_the_foot_of_the_Eiffel_Tower-Aux_pieds_de_la_Tour_Eiffel.jpg",
        "assets/collections/Paris~2024/Eiffel_Tower/Eiffel_Tower_at_night-Tour_Eiffel_dans_la_nuit.jpg",
        "assets/collections/Paris~2024/Eiffel_Tower/Eiffel_Tower_through_the_leaves-Tour_Eiffel_à_travers_les_feuilles.jpg",
        "assets/collections/Paris~2024/Eiffel_Tower/Vintage_Eiffel_Tower.jpg"
      ],
      "photos": [
        {
          "filename": "Galeries Lafayettes.jpg",
          "src": "assets/collections/Paris~2024/Galeries Lafayettes.jpg",
          "label": {
            "en": "Galeries Lafayettes",
            "fr": "Galeries Lafayettes"
          }
        },
        {
          "filename": "Hôtel_des_Invalides_through_the_gate-Hôtel_des_Invalides_à_travers_la_grille.jpg",
          "src": "assets/collections/Paris~2024/Hôtel_des_Invalides_through_the_gate-Hôtel_des_Invalides_à_travers_la_grille.jpg",
          "label": {
            "en": "Hôtel des Invalides through the gate",
            "fr": "Hôtel des Invalides à travers la grille"
          }
        },
        {
          "filename": "Metro.jpg",
          "src": "assets/collections/Paris~2024/Metro.jpg",
          "label": {
            "en": "Metro",
            "fr": "Metro"
          }
        }
      ],
      "subcollections": [
        {
          "id": "Eiffel_Tower",
          "title": {
            "en": "Eiffel Tower",
            "fr": "Eiffel Tower"
          },
          "description": null,
          "photos": [
            {
              "filename": "At_the_foot_of_the_Eiffel_Tower-Aux_pieds_de_la_Tour_Eiffel.jpg",
              "src": "assets/collections/Paris~2024/Eiffel_Tower/At_the_foot_of_the_Eiffel_Tower-Aux_pieds_de_la_Tour_Eiffel.jpg",
              "label": {
                "en": "At the foot of the Eiffel Tower",
                "fr": "Aux pieds de la Tour Eiffel"
              }
            },
            {
              "filename": "Eiffel_Tower_at_night-Tour_Eiffel_dans_la_nuit.jpg",
              "src": "assets/collections/Paris~2024/Eiffel_Tower/Eiffel_Tower_at_night-Tour_Eiffel_dans_la_nuit.jpg",
              "label": {
                "en": "Eiffel Tower at night",
                "fr": "Tour Eiffel dans la nuit"
              }
            },
            {
              "filename": "Eiffel_Tower_through_the_leaves-Tour_Eiffel_à_travers_les_feuilles.jpg",
              "src": "assets/collections/Paris~2024/Eiffel_Tower/Eiffel_Tower_through_the_leaves-Tour_Eiffel_à_travers_les_feuilles.jpg",
              "label": {
                "en": "Eiffel Tower through the leaves",
                "fr": "Tour Eiffel à travers les feuilles"
              }
            },
            {
              "filename": "Vintage_Eiffel_Tower.jpg",
              "src": "assets/collections/Paris~2024/Eiffel_Tower/Vintage_Eiffel_Tower.jpg",
              "label": {
                "en": "Vintage Eiffel Tower",
                "fr": "Vintage Eiffel Tower"
              }
            }
          ]
        }
      ],
      "allPhotos": [
        {
          "filename": "Galeries Lafayettes.jpg",
          "src": "assets/collections/Paris~2024/Galeries Lafayettes.jpg",
          "label": {
            "en": "Galeries Lafayettes",
            "fr": "Galeries Lafayettes"
          }
        },
        {
          "filename": "Hôtel_des_Invalides_through_the_gate-Hôtel_des_Invalides_à_travers_la_grille.jpg",
          "src": "assets/collections/Paris~2024/Hôtel_des_Invalides_through_the_gate-Hôtel_des_Invalides_à_travers_la_grille.jpg",
          "label": {
            "en": "Hôtel des Invalides through the gate",
            "fr": "Hôtel des Invalides à travers la grille"
          }
        },
        {
          "filename": "Metro.jpg",
          "src": "assets/collections/Paris~2024/Metro.jpg",
          "label": {
            "en": "Metro",
            "fr": "Metro"
          }
        },
        {
          "filename": "At_the_foot_of_the_Eiffel_Tower-Aux_pieds_de_la_Tour_Eiffel.jpg",
          "src": "assets/collections/Paris~2024/Eiffel_Tower/At_the_foot_of_the_Eiffel_Tower-Aux_pieds_de_la_Tour_Eiffel.jpg",
          "label": {
            "en": "At the foot of the Eiffel Tower",
            "fr": "Aux pieds de la Tour Eiffel"
          }
        },
        {
          "filename": "Eiffel_Tower_at_night-Tour_Eiffel_dans_la_nuit.jpg",
          "src": "assets/collections/Paris~2024/Eiffel_Tower/Eiffel_Tower_at_night-Tour_Eiffel_dans_la_nuit.jpg",
          "label": {
            "en": "Eiffel Tower at night",
            "fr": "Tour Eiffel dans la nuit"
          }
        },
        {
          "filename": "Eiffel_Tower_through_the_leaves-Tour_Eiffel_à_travers_les_feuilles.jpg",
          "src": "assets/collections/Paris~2024/Eiffel_Tower/Eiffel_Tower_through_the_leaves-Tour_Eiffel_à_travers_les_feuilles.jpg",
          "label": {
            "en": "Eiffel Tower through the leaves",
            "fr": "Tour Eiffel à travers les feuilles"
          }
        },
        {
          "filename": "Vintage_Eiffel_Tower.jpg",
          "src": "assets/collections/Paris~2024/Eiffel_Tower/Vintage_Eiffel_Tower.jpg",
          "label": {
            "en": "Vintage Eiffel Tower",
            "fr": "Vintage Eiffel Tower"
          }
        }
      ]
    },
    {
      "id": "Saint_Lary~2025",
      "folderName": "Saint_Lary~2025",
      "title": {
        "en": "Saint Lary",
        "fr": "Saint Lary"
      },
      "date": "2025",
      "description": {
        "en": "A trip to the mountains with an university association.",
        "fr": "Sortie au zoo avec une association universitaire."
      },
      "covers": [
        "assets/collections/Saint_Lary~2025/Alone_facing_the_void-Seul_face_au_vide.jpg",
        "assets/collections/Saint_Lary~2025/Car_frozen_in_snow-Voiture-figée-dans-la-neige.jpg",
        "assets/collections/Saint_Lary~2025/Mountainous_landscape-Paysage_montagneux.jpg",
        "assets/collections/Saint_Lary~2025/Mountainous_landscape_2-Paysage_montagneux_2.jpg",
        "assets/collections/Saint_Lary~2025/Mountainous_landscape_3-Paysage_montagneux_3.jpg",
        "assets/collections/Saint_Lary~2025/Mountainous_landscape_4-Paysage_montagneux_4.jpg",
        "assets/collections/Saint_Lary~2025/Mountainous_landscape_5-Paysage_montagneux_5.jpg",
        "assets/collections/Saint_Lary~2025/Parking_lot_covered_in_snow-Parking_enneigé.jpg",
        "assets/collections/Saint_Lary~2025/Solitary_fir_tree-Sapin_solitaire.jpg"
      ],
      "photos": [
        {
          "filename": "Alone_facing_the_void-Seul_face_au_vide.jpg",
          "src": "assets/collections/Saint_Lary~2025/Alone_facing_the_void-Seul_face_au_vide.jpg",
          "label": {
            "en": "Alone facing the void",
            "fr": "Seul face au vide"
          }
        },
        {
          "filename": "Car_frozen_in_snow-Voiture-figée-dans-la-neige.jpg",
          "src": "assets/collections/Saint_Lary~2025/Car_frozen_in_snow-Voiture-figée-dans-la-neige.jpg",
          "label": {
            "en": "Car frozen in snow",
            "fr": "Voiture-figée-dans-la-neige"
          }
        },
        {
          "filename": "Mountainous_landscape-Paysage_montagneux.jpg",
          "src": "assets/collections/Saint_Lary~2025/Mountainous_landscape-Paysage_montagneux.jpg",
          "label": {
            "en": "Mountainous landscape",
            "fr": "Paysage montagneux"
          }
        },
        {
          "filename": "Mountainous_landscape_2-Paysage_montagneux_2.jpg",
          "src": "assets/collections/Saint_Lary~2025/Mountainous_landscape_2-Paysage_montagneux_2.jpg",
          "label": {
            "en": "Mountainous landscape 2",
            "fr": "Paysage montagneux 2"
          }
        },
        {
          "filename": "Mountainous_landscape_3-Paysage_montagneux_3.jpg",
          "src": "assets/collections/Saint_Lary~2025/Mountainous_landscape_3-Paysage_montagneux_3.jpg",
          "label": {
            "en": "Mountainous landscape 3",
            "fr": "Paysage montagneux 3"
          }
        },
        {
          "filename": "Mountainous_landscape_4-Paysage_montagneux_4.jpg",
          "src": "assets/collections/Saint_Lary~2025/Mountainous_landscape_4-Paysage_montagneux_4.jpg",
          "label": {
            "en": "Mountainous landscape 4",
            "fr": "Paysage montagneux 4"
          }
        },
        {
          "filename": "Mountainous_landscape_5-Paysage_montagneux_5.jpg",
          "src": "assets/collections/Saint_Lary~2025/Mountainous_landscape_5-Paysage_montagneux_5.jpg",
          "label": {
            "en": "Mountainous landscape 5",
            "fr": "Paysage montagneux 5"
          }
        },
        {
          "filename": "Parking_lot_covered_in_snow-Parking_enneigé.jpg",
          "src": "assets/collections/Saint_Lary~2025/Parking_lot_covered_in_snow-Parking_enneigé.jpg",
          "label": {
            "en": "Parking lot covered in snow",
            "fr": "Parking enneigé"
          }
        },
        {
          "filename": "Solitary_fir_tree-Sapin_solitaire.jpg",
          "src": "assets/collections/Saint_Lary~2025/Solitary_fir_tree-Sapin_solitaire.jpg",
          "label": {
            "en": "Solitary fir tree",
            "fr": "Sapin solitaire"
          }
        }
      ],
      "subcollections": [],
      "allPhotos": [
        {
          "filename": "Alone_facing_the_void-Seul_face_au_vide.jpg",
          "src": "assets/collections/Saint_Lary~2025/Alone_facing_the_void-Seul_face_au_vide.jpg",
          "label": {
            "en": "Alone facing the void",
            "fr": "Seul face au vide"
          }
        },
        {
          "filename": "Car_frozen_in_snow-Voiture-figée-dans-la-neige.jpg",
          "src": "assets/collections/Saint_Lary~2025/Car_frozen_in_snow-Voiture-figée-dans-la-neige.jpg",
          "label": {
            "en": "Car frozen in snow",
            "fr": "Voiture-figée-dans-la-neige"
          }
        },
        {
          "filename": "Mountainous_landscape-Paysage_montagneux.jpg",
          "src": "assets/collections/Saint_Lary~2025/Mountainous_landscape-Paysage_montagneux.jpg",
          "label": {
            "en": "Mountainous landscape",
            "fr": "Paysage montagneux"
          }
        },
        {
          "filename": "Mountainous_landscape_2-Paysage_montagneux_2.jpg",
          "src": "assets/collections/Saint_Lary~2025/Mountainous_landscape_2-Paysage_montagneux_2.jpg",
          "label": {
            "en": "Mountainous landscape 2",
            "fr": "Paysage montagneux 2"
          }
        },
        {
          "filename": "Mountainous_landscape_3-Paysage_montagneux_3.jpg",
          "src": "assets/collections/Saint_Lary~2025/Mountainous_landscape_3-Paysage_montagneux_3.jpg",
          "label": {
            "en": "Mountainous landscape 3",
            "fr": "Paysage montagneux 3"
          }
        },
        {
          "filename": "Mountainous_landscape_4-Paysage_montagneux_4.jpg",
          "src": "assets/collections/Saint_Lary~2025/Mountainous_landscape_4-Paysage_montagneux_4.jpg",
          "label": {
            "en": "Mountainous landscape 4",
            "fr": "Paysage montagneux 4"
          }
        },
        {
          "filename": "Mountainous_landscape_5-Paysage_montagneux_5.jpg",
          "src": "assets/collections/Saint_Lary~2025/Mountainous_landscape_5-Paysage_montagneux_5.jpg",
          "label": {
            "en": "Mountainous landscape 5",
            "fr": "Paysage montagneux 5"
          }
        },
        {
          "filename": "Parking_lot_covered_in_snow-Parking_enneigé.jpg",
          "src": "assets/collections/Saint_Lary~2025/Parking_lot_covered_in_snow-Parking_enneigé.jpg",
          "label": {
            "en": "Parking lot covered in snow",
            "fr": "Parking enneigé"
          }
        },
        {
          "filename": "Solitary_fir_tree-Sapin_solitaire.jpg",
          "src": "assets/collections/Saint_Lary~2025/Solitary_fir_tree-Sapin_solitaire.jpg",
          "label": {
            "en": "Solitary fir tree",
            "fr": "Sapin solitaire"
          }
        }
      ]
    },
    {
      "id": "San_Francisco~2024",
      "folderName": "San_Francisco~2024",
      "title": {
        "en": "San Francisco",
        "fr": "San Francisco"
      },
      "date": "2024",
      "description": {
        "en": "---\ntitle: San Francisco\ndate: October 2024\nlocation: San Francisco, CA\ntype: Personal\ntrip: true\n---\nA long weekend on the west coast. Fog, bridges, and light that never quite does what you expect.",
        "fr": "---\ntitle: San Francisco\ndate: October 2024\nlocation: San Francisco, CA\ntype: Personal\ntrip: true\n---\nA long weekend on the west coast. Fog, bridges, and light that never quite does what you expect."
      },
      "covers": [],
      "photos": [],
      "subcollections": [],
      "allPhotos": []
    },
    {
      "id": "Spain-Espagne~2025",
      "folderName": "Spain-Espagne~2025",
      "title": {
        "en": "Spain",
        "fr": "Espagne"
      },
      "date": "2025",
      "description": {
        "en": "Vacation in Spain with friends.",
        "fr": "Vacances en Espagne entre amis."
      },
      "covers": [
        "assets/collections/Spain-Espagne~2025/Bilbao/Lezama_Leguizamon_House_at_Bilbao-Maison_Lezama_Leguizamon_à_Bilbao.jpg",
        "assets/collections/Spain-Espagne~2025/San Juan de Gaztelugatxe/A_flower_contemplating_the_sunset-Une_fleur_contemplant_le_coucher_de_soleil.jpg",
        "assets/collections/Spain-Espagne~2025/San Juan de Gaztelugatxe/Cliff-Falaise.jpg",
        "assets/collections/Spain-Espagne~2025/San Juan de Gaztelugatxe/Horizon_over_Bentalde-Horizon_sur_Bentalde.jpg",
        "assets/collections/Spain-Espagne~2025/San Juan de Gaztelugatxe/Rock_on_the_water-Rocher_sur_l'eau.jpg",
        "assets/collections/Spain-Espagne~2025/San Juan de Gaztelugatxe/Rock_on_the_water_2-Rocher_sur_l'eau_2.jpg",
        "assets/collections/Spain-Espagne~2025/San Juan de Gaztelugatxe/Stairs_of_Gaztelugatxe-Escaliers_de_Gaztelugatxe.jpg",
        "assets/collections/Spain-Espagne~2025/San Juan de Gaztelugatxe/View_of_Bentalde-Vue_sur_Bentalde.jpg",
        "assets/collections/Spain-Espagne~2025/San Sebastián/Bird's_eye_view_of_the_beach-Vue_plongeante_sur_la_plage.jpg",
        "assets/collections/Spain-Espagne~2025/San Sebastián/Diocesan_Seminary_of_San_Sebastián.jpg",
        "assets/collections/Spain-Espagne~2025/San Sebastián/Focus_on_a_sailing_boat-Focus_sur_un_voilier.jpg",
        "assets/collections/Spain-Espagne~2025/San Sebastián/People_walking_along_the_coast-Des_passants_sur_la_côté.jpg",
        "assets/collections/Spain-Espagne~2025/San Sebastián/San_Sebastián_between_two_walls-San_Sebastián_entre_deux_murs.jpg",
        "assets/collections/Spain-Espagne~2025/San Sebastián/The_horizon_of_San_Sebastián-L'horizon_de_San_Sebastián.jpg",
        "assets/collections/Spain-Espagne~2025/Zarautz/Reflection_of_Zarautz_in_the_evening-Réflexion_de_Zarautz_en_soirée.jpg",
        "assets/collections/Spain-Espagne~2025/Zarautz/Street_lamp-Lampadaire.jpg",
        "assets/collections/Spain-Espagne~2025/Zarautz/Sunset-Coucher_de_soleil.jpg",
        "assets/collections/Spain-Espagne~2025/Zarautz/Sunset_2-Coucher_de_soleil_2.jpg",
        "assets/collections/Spain-Espagne~2025/Zarautz/Sunset_3-Coucher_de_soleil_3.jpg",
        "assets/collections/Spain-Espagne~2025/Zarautz/Two_friends_on_the_beach-Deux_amis_sur_la_plage.jpg"
      ],
      "photos": [],
      "subcollections": [
        {
          "id": "Bilbao",
          "title": {
            "en": "Bilbao",
            "fr": "Bilbao"
          },
          "description": null,
          "photos": [
            {
              "filename": "Lezama_Leguizamon_House_at_Bilbao-Maison_Lezama_Leguizamon_à_Bilbao.jpg",
              "src": "assets/collections/Spain-Espagne~2025/Bilbao/Lezama_Leguizamon_House_at_Bilbao-Maison_Lezama_Leguizamon_à_Bilbao.jpg",
              "label": {
                "en": "Lezama Leguizamon House at Bilbao",
                "fr": "Maison Lezama Leguizamon à Bilbao"
              }
            }
          ]
        },
        {
          "id": "San_Juan_de_Gaztelugatxe",
          "title": {
            "en": "San Juan de Gaztelugatxe",
            "fr": "San Juan de Gaztelugatxe"
          },
          "description": null,
          "photos": [
            {
              "filename": "A_flower_contemplating_the_sunset-Une_fleur_contemplant_le_coucher_de_soleil.jpg",
              "src": "assets/collections/Spain-Espagne~2025/San Juan de Gaztelugatxe/A_flower_contemplating_the_sunset-Une_fleur_contemplant_le_coucher_de_soleil.jpg",
              "label": {
                "en": "A flower contemplating the sunset",
                "fr": "Une fleur contemplant le coucher de soleil"
              }
            },
            {
              "filename": "Cliff-Falaise.jpg",
              "src": "assets/collections/Spain-Espagne~2025/San Juan de Gaztelugatxe/Cliff-Falaise.jpg",
              "label": {
                "en": "Cliff",
                "fr": "Falaise"
              }
            },
            {
              "filename": "Horizon_over_Bentalde-Horizon_sur_Bentalde.jpg",
              "src": "assets/collections/Spain-Espagne~2025/San Juan de Gaztelugatxe/Horizon_over_Bentalde-Horizon_sur_Bentalde.jpg",
              "label": {
                "en": "Horizon over Bentalde",
                "fr": "Horizon sur Bentalde"
              }
            },
            {
              "filename": "Rock_on_the_water-Rocher_sur_l'eau.jpg",
              "src": "assets/collections/Spain-Espagne~2025/San Juan de Gaztelugatxe/Rock_on_the_water-Rocher_sur_l'eau.jpg",
              "label": {
                "en": "Rock on the water",
                "fr": "Rocher sur l'eau"
              }
            },
            {
              "filename": "Rock_on_the_water_2-Rocher_sur_l'eau_2.jpg",
              "src": "assets/collections/Spain-Espagne~2025/San Juan de Gaztelugatxe/Rock_on_the_water_2-Rocher_sur_l'eau_2.jpg",
              "label": {
                "en": "Rock on the water 2",
                "fr": "Rocher sur l'eau 2"
              }
            },
            {
              "filename": "Stairs_of_Gaztelugatxe-Escaliers_de_Gaztelugatxe.jpg",
              "src": "assets/collections/Spain-Espagne~2025/San Juan de Gaztelugatxe/Stairs_of_Gaztelugatxe-Escaliers_de_Gaztelugatxe.jpg",
              "label": {
                "en": "Stairs of Gaztelugatxe",
                "fr": "Escaliers de Gaztelugatxe"
              }
            },
            {
              "filename": "View_of_Bentalde-Vue_sur_Bentalde.jpg",
              "src": "assets/collections/Spain-Espagne~2025/San Juan de Gaztelugatxe/View_of_Bentalde-Vue_sur_Bentalde.jpg",
              "label": {
                "en": "View of Bentalde",
                "fr": "Vue sur Bentalde"
              }
            }
          ]
        },
        {
          "id": "San_Sebastián",
          "title": {
            "en": "San Sebastián",
            "fr": "San Sebastián"
          },
          "description": null,
          "photos": [
            {
              "filename": "Bird's_eye_view_of_the_beach-Vue_plongeante_sur_la_plage.jpg",
              "src": "assets/collections/Spain-Espagne~2025/San Sebastián/Bird's_eye_view_of_the_beach-Vue_plongeante_sur_la_plage.jpg",
              "label": {
                "en": "Bird's eye view of the beach",
                "fr": "Vue plongeante sur la plage"
              }
            },
            {
              "filename": "Diocesan_Seminary_of_San_Sebastián.jpg",
              "src": "assets/collections/Spain-Espagne~2025/San Sebastián/Diocesan_Seminary_of_San_Sebastián.jpg",
              "label": {
                "en": "Diocesan Seminary of San Sebastián",
                "fr": "Diocesan Seminary of San Sebastián"
              }
            },
            {
              "filename": "Focus_on_a_sailing_boat-Focus_sur_un_voilier.jpg",
              "src": "assets/collections/Spain-Espagne~2025/San Sebastián/Focus_on_a_sailing_boat-Focus_sur_un_voilier.jpg",
              "label": {
                "en": "Focus on a sailing boat",
                "fr": "Focus sur un voilier"
              }
            },
            {
              "filename": "People_walking_along_the_coast-Des_passants_sur_la_côté.jpg",
              "src": "assets/collections/Spain-Espagne~2025/San Sebastián/People_walking_along_the_coast-Des_passants_sur_la_côté.jpg",
              "label": {
                "en": "People walking along the coast",
                "fr": "Des passants sur la côté"
              }
            },
            {
              "filename": "San_Sebastián_between_two_walls-San_Sebastián_entre_deux_murs.jpg",
              "src": "assets/collections/Spain-Espagne~2025/San Sebastián/San_Sebastián_between_two_walls-San_Sebastián_entre_deux_murs.jpg",
              "label": {
                "en": "San Sebastián between two walls",
                "fr": "San Sebastián entre deux murs"
              }
            },
            {
              "filename": "The_horizon_of_San_Sebastián-L'horizon_de_San_Sebastián.jpg",
              "src": "assets/collections/Spain-Espagne~2025/San Sebastián/The_horizon_of_San_Sebastián-L'horizon_de_San_Sebastián.jpg",
              "label": {
                "en": "The horizon of San Sebastián",
                "fr": "L'horizon de San Sebastián"
              }
            }
          ]
        },
        {
          "id": "Zarautz",
          "title": {
            "en": "Zarautz",
            "fr": "Zarautz"
          },
          "description": null,
          "photos": [
            {
              "filename": "Reflection_of_Zarautz_in_the_evening-Réflexion_de_Zarautz_en_soirée.jpg",
              "src": "assets/collections/Spain-Espagne~2025/Zarautz/Reflection_of_Zarautz_in_the_evening-Réflexion_de_Zarautz_en_soirée.jpg",
              "label": {
                "en": "Reflection of Zarautz in the evening",
                "fr": "Réflexion de Zarautz en soirée"
              }
            },
            {
              "filename": "Street_lamp-Lampadaire.jpg",
              "src": "assets/collections/Spain-Espagne~2025/Zarautz/Street_lamp-Lampadaire.jpg",
              "label": {
                "en": "Street lamp",
                "fr": "Lampadaire"
              }
            },
            {
              "filename": "Sunset-Coucher_de_soleil.jpg",
              "src": "assets/collections/Spain-Espagne~2025/Zarautz/Sunset-Coucher_de_soleil.jpg",
              "label": {
                "en": "Sunset",
                "fr": "Coucher de soleil"
              }
            },
            {
              "filename": "Sunset_2-Coucher_de_soleil_2.jpg",
              "src": "assets/collections/Spain-Espagne~2025/Zarautz/Sunset_2-Coucher_de_soleil_2.jpg",
              "label": {
                "en": "Sunset 2",
                "fr": "Coucher de soleil 2"
              }
            },
            {
              "filename": "Sunset_3-Coucher_de_soleil_3.jpg",
              "src": "assets/collections/Spain-Espagne~2025/Zarautz/Sunset_3-Coucher_de_soleil_3.jpg",
              "label": {
                "en": "Sunset 3",
                "fr": "Coucher de soleil 3"
              }
            },
            {
              "filename": "Two_friends_on_the_beach-Deux_amis_sur_la_plage.jpg",
              "src": "assets/collections/Spain-Espagne~2025/Zarautz/Two_friends_on_the_beach-Deux_amis_sur_la_plage.jpg",
              "label": {
                "en": "Two friends on the beach",
                "fr": "Deux amis sur la plage"
              }
            }
          ]
        }
      ],
      "allPhotos": [
        {
          "filename": "Lezama_Leguizamon_House_at_Bilbao-Maison_Lezama_Leguizamon_à_Bilbao.jpg",
          "src": "assets/collections/Spain-Espagne~2025/Bilbao/Lezama_Leguizamon_House_at_Bilbao-Maison_Lezama_Leguizamon_à_Bilbao.jpg",
          "label": {
            "en": "Lezama Leguizamon House at Bilbao",
            "fr": "Maison Lezama Leguizamon à Bilbao"
          }
        },
        {
          "filename": "A_flower_contemplating_the_sunset-Une_fleur_contemplant_le_coucher_de_soleil.jpg",
          "src": "assets/collections/Spain-Espagne~2025/San Juan de Gaztelugatxe/A_flower_contemplating_the_sunset-Une_fleur_contemplant_le_coucher_de_soleil.jpg",
          "label": {
            "en": "A flower contemplating the sunset",
            "fr": "Une fleur contemplant le coucher de soleil"
          }
        },
        {
          "filename": "Cliff-Falaise.jpg",
          "src": "assets/collections/Spain-Espagne~2025/San Juan de Gaztelugatxe/Cliff-Falaise.jpg",
          "label": {
            "en": "Cliff",
            "fr": "Falaise"
          }
        },
        {
          "filename": "Horizon_over_Bentalde-Horizon_sur_Bentalde.jpg",
          "src": "assets/collections/Spain-Espagne~2025/San Juan de Gaztelugatxe/Horizon_over_Bentalde-Horizon_sur_Bentalde.jpg",
          "label": {
            "en": "Horizon over Bentalde",
            "fr": "Horizon sur Bentalde"
          }
        },
        {
          "filename": "Rock_on_the_water-Rocher_sur_l'eau.jpg",
          "src": "assets/collections/Spain-Espagne~2025/San Juan de Gaztelugatxe/Rock_on_the_water-Rocher_sur_l'eau.jpg",
          "label": {
            "en": "Rock on the water",
            "fr": "Rocher sur l'eau"
          }
        },
        {
          "filename": "Rock_on_the_water_2-Rocher_sur_l'eau_2.jpg",
          "src": "assets/collections/Spain-Espagne~2025/San Juan de Gaztelugatxe/Rock_on_the_water_2-Rocher_sur_l'eau_2.jpg",
          "label": {
            "en": "Rock on the water 2",
            "fr": "Rocher sur l'eau 2"
          }
        },
        {
          "filename": "Stairs_of_Gaztelugatxe-Escaliers_de_Gaztelugatxe.jpg",
          "src": "assets/collections/Spain-Espagne~2025/San Juan de Gaztelugatxe/Stairs_of_Gaztelugatxe-Escaliers_de_Gaztelugatxe.jpg",
          "label": {
            "en": "Stairs of Gaztelugatxe",
            "fr": "Escaliers de Gaztelugatxe"
          }
        },
        {
          "filename": "View_of_Bentalde-Vue_sur_Bentalde.jpg",
          "src": "assets/collections/Spain-Espagne~2025/San Juan de Gaztelugatxe/View_of_Bentalde-Vue_sur_Bentalde.jpg",
          "label": {
            "en": "View of Bentalde",
            "fr": "Vue sur Bentalde"
          }
        },
        {
          "filename": "Bird's_eye_view_of_the_beach-Vue_plongeante_sur_la_plage.jpg",
          "src": "assets/collections/Spain-Espagne~2025/San Sebastián/Bird's_eye_view_of_the_beach-Vue_plongeante_sur_la_plage.jpg",
          "label": {
            "en": "Bird's eye view of the beach",
            "fr": "Vue plongeante sur la plage"
          }
        },
        {
          "filename": "Diocesan_Seminary_of_San_Sebastián.jpg",
          "src": "assets/collections/Spain-Espagne~2025/San Sebastián/Diocesan_Seminary_of_San_Sebastián.jpg",
          "label": {
            "en": "Diocesan Seminary of San Sebastián",
            "fr": "Diocesan Seminary of San Sebastián"
          }
        },
        {
          "filename": "Focus_on_a_sailing_boat-Focus_sur_un_voilier.jpg",
          "src": "assets/collections/Spain-Espagne~2025/San Sebastián/Focus_on_a_sailing_boat-Focus_sur_un_voilier.jpg",
          "label": {
            "en": "Focus on a sailing boat",
            "fr": "Focus sur un voilier"
          }
        },
        {
          "filename": "People_walking_along_the_coast-Des_passants_sur_la_côté.jpg",
          "src": "assets/collections/Spain-Espagne~2025/San Sebastián/People_walking_along_the_coast-Des_passants_sur_la_côté.jpg",
          "label": {
            "en": "People walking along the coast",
            "fr": "Des passants sur la côté"
          }
        },
        {
          "filename": "San_Sebastián_between_two_walls-San_Sebastián_entre_deux_murs.jpg",
          "src": "assets/collections/Spain-Espagne~2025/San Sebastián/San_Sebastián_between_two_walls-San_Sebastián_entre_deux_murs.jpg",
          "label": {
            "en": "San Sebastián between two walls",
            "fr": "San Sebastián entre deux murs"
          }
        },
        {
          "filename": "The_horizon_of_San_Sebastián-L'horizon_de_San_Sebastián.jpg",
          "src": "assets/collections/Spain-Espagne~2025/San Sebastián/The_horizon_of_San_Sebastián-L'horizon_de_San_Sebastián.jpg",
          "label": {
            "en": "The horizon of San Sebastián",
            "fr": "L'horizon de San Sebastián"
          }
        },
        {
          "filename": "Reflection_of_Zarautz_in_the_evening-Réflexion_de_Zarautz_en_soirée.jpg",
          "src": "assets/collections/Spain-Espagne~2025/Zarautz/Reflection_of_Zarautz_in_the_evening-Réflexion_de_Zarautz_en_soirée.jpg",
          "label": {
            "en": "Reflection of Zarautz in the evening",
            "fr": "Réflexion de Zarautz en soirée"
          }
        },
        {
          "filename": "Street_lamp-Lampadaire.jpg",
          "src": "assets/collections/Spain-Espagne~2025/Zarautz/Street_lamp-Lampadaire.jpg",
          "label": {
            "en": "Street lamp",
            "fr": "Lampadaire"
          }
        },
        {
          "filename": "Sunset-Coucher_de_soleil.jpg",
          "src": "assets/collections/Spain-Espagne~2025/Zarautz/Sunset-Coucher_de_soleil.jpg",
          "label": {
            "en": "Sunset",
            "fr": "Coucher de soleil"
          }
        },
        {
          "filename": "Sunset_2-Coucher_de_soleil_2.jpg",
          "src": "assets/collections/Spain-Espagne~2025/Zarautz/Sunset_2-Coucher_de_soleil_2.jpg",
          "label": {
            "en": "Sunset 2",
            "fr": "Coucher de soleil 2"
          }
        },
        {
          "filename": "Sunset_3-Coucher_de_soleil_3.jpg",
          "src": "assets/collections/Spain-Espagne~2025/Zarautz/Sunset_3-Coucher_de_soleil_3.jpg",
          "label": {
            "en": "Sunset 3",
            "fr": "Coucher de soleil 3"
          }
        },
        {
          "filename": "Two_friends_on_the_beach-Deux_amis_sur_la_plage.jpg",
          "src": "assets/collections/Spain-Espagne~2025/Zarautz/Two_friends_on_the_beach-Deux_amis_sur_la_plage.jpg",
          "label": {
            "en": "Two friends on the beach",
            "fr": "Deux amis sur la plage"
          }
        }
      ]
    }
  ],
  "homeFeed": [
    {
      "filename": "Alone_facing_the_void-Seul_face_au_vide.jpg",
      "src": "assets/collections/Saint_Lary~2025/Alone_facing_the_void-Seul_face_au_vide.jpg",
      "label": {
        "en": "Alone facing the void",
        "fr": "Seul face au vide"
      },
      "collectionId": "Saint_Lary~2025"
    },
    {
      "filename": "Third_Quarter-Dernier_quartier.jpg",
      "src": "assets/collections/Moon~2025/Third_Quarter-Dernier_quartier.jpg",
      "label": {
        "en": "Third Quarter",
        "fr": "Dernier quartier"
      },
      "collectionId": "Moon~2025"
    },
    {
      "filename": "Rock_on_the_water_2-Rocher_sur_l'eau_2.jpg",
      "src": "assets/collections/Spain-Espagne~2025/San Juan de Gaztelugatxe/Rock_on_the_water_2-Rocher_sur_l'eau_2.jpg",
      "label": {
        "en": "Rock on the water 2",
        "fr": "Rocher sur l'eau 2"
      },
      "collectionId": "Spain-Espagne~2025"
    },
    {
      "filename": "Yellowbanded_Sweetlips-Gaterin_à_bandes_jaunes.jpg",
      "src": "assets/collections/Biarritz~2025/Aquarium/Yellowbanded_Sweetlips-Gaterin_à_bandes_jaunes.jpg",
      "label": {
        "en": "Yellowbanded Sweetlips",
        "fr": "Gaterin à bandes jaunes"
      },
      "collectionId": "Biarritz~2025"
    },
    {
      "filename": "People_walking_along_the_coast-Des_passants_sur_la_côté.jpg",
      "src": "assets/collections/Spain-Espagne~2025/San Sebastián/People_walking_along_the_coast-Des_passants_sur_la_côté.jpg",
      "label": {
        "en": "People walking along the coast",
        "fr": "Des passants sur la côté"
      },
      "collectionId": "Spain-Espagne~2025"
    },
    {
      "filename": "A_flower_contemplating_the_sunset-Une_fleur_contemplant_le_coucher_de_soleil.jpg",
      "src": "assets/collections/Spain-Espagne~2025/San Juan de Gaztelugatxe/A_flower_contemplating_the_sunset-Une_fleur_contemplant_le_coucher_de_soleil.jpg",
      "label": {
        "en": "A flower contemplating the sunset",
        "fr": "Une fleur contemplant le coucher de soleil"
      },
      "collectionId": "Spain-Espagne~2025"
    },
    {
      "filename": "Flamingo-Flamand_rose.jpg",
      "src": "assets/collections/Asson_Zoo-Zoo_d'Asson~2024/Animals-Animaux/Flamingo-Flamand_rose.jpg",
      "label": {
        "en": "Flamingo",
        "fr": "Flamand rose"
      },
      "collectionId": "Asson_Zoo-Zoo_d'Asson~2024"
    },
    {
      "filename": "Yellow_and_blueback_Fusilier-Fusilier_à_dos_jaune_et_bleu.jpg",
      "src": "assets/collections/Biarritz~2025/Aquarium/Yellow_and_blueback_Fusilier-Fusilier_à_dos_jaune_et_bleu.jpg",
      "label": {
        "en": "Yellow and blueback Fusilier",
        "fr": "Fusilier à dos jaune et bleu"
      },
      "collectionId": "Biarritz~2025"
    },
    {
      "filename": "Hôtel_des_Invalides_through_the_gate-Hôtel_des_Invalides_à_travers_la_grille.jpg",
      "src": "assets/collections/Paris~2024/Hôtel_des_Invalides_through_the_gate-Hôtel_des_Invalides_à_travers_la_grille.jpg",
      "label": {
        "en": "Hôtel des Invalides through the gate",
        "fr": "Hôtel des Invalides à travers la grille"
      },
      "collectionId": "Paris~2024"
    },
    {
      "filename": "Waxing_Gibbous-Lune_Gibbeuse.jpg",
      "src": "assets/collections/Moon~2025/Waxing_Gibbous-Lune_Gibbeuse.jpg",
      "label": {
        "en": "Waxing Gibbous",
        "fr": "Lune Gibbeuse"
      },
      "collectionId": "Moon~2025"
    },
    {
      "filename": "Sky_in_fire-Ciel_en_feu.jpg",
      "src": "assets/collections/Airplanes-Avions~2025/Sky_in_fire-Ciel_en_feu.jpg",
      "label": {
        "en": "Sky in fire",
        "fr": "Ciel en feu"
      },
      "collectionId": "Airplanes-Avions~2025"
    },
    {
      "filename": "A320.jpg",
      "src": "assets/collections/Airplanes-Avions~2025/A320.jpg",
      "label": {
        "en": "A320",
        "fr": "A320"
      },
      "collectionId": "Airplanes-Avions~2025"
    },
    {
      "filename": "Galeries Lafayettes.jpg",
      "src": "assets/collections/Paris~2024/Galeries Lafayettes.jpg",
      "label": {
        "en": "Galeries Lafayettes",
        "fr": "Galeries Lafayettes"
      },
      "collectionId": "Paris~2024"
    },
    {
      "filename": "Rocher_de_la_Vierge.jpg",
      "src": "assets/collections/Biarritz~2025/Walk_in_the_city-Balade_en_ville/Rocher_de_la_Vierge.jpg",
      "label": {
        "en": "Rocher de la Vierge",
        "fr": "Rocher de la Vierge"
      },
      "collectionId": "Biarritz~2025"
    },
    {
      "filename": "Dog_with_different_colored_eyes_2-Chien_aux_yeux_vairons_2.jpg",
      "src": "assets/collections/Barèges~2025/Dog_with_different_colored_eyes_2-Chien_aux_yeux_vairons_2.jpg",
      "label": {
        "en": "Dog with different colored eyes 2",
        "fr": "Chien aux yeux vairons 2"
      },
      "collectionId": "Barèges~2025"
    },
    {
      "filename": "Sheep_facing_me-Mouton_face_à_moi.jpg",
      "src": "assets/collections/Barèges~2025/Sheep_facing_me-Mouton_face_à_moi.jpg",
      "label": {
        "en": "Sheep facing me",
        "fr": "Mouton face à moi"
      },
      "collectionId": "Barèges~2025"
    },
    {
      "filename": "Red_panda-Panda_roux.jpg",
      "src": "assets/collections/Asson_Zoo-Zoo_d'Asson~2024/Animals-Animaux/Red_panda-Panda_roux.jpg",
      "label": {
        "en": "Red panda",
        "fr": "Panda roux"
      },
      "collectionId": "Asson_Zoo-Zoo_d'Asson~2024"
    },
    {
      "filename": "Vintage_Eiffel_Tower.jpg",
      "src": "assets/collections/Paris~2024/Eiffel_Tower/Vintage_Eiffel_Tower.jpg",
      "label": {
        "en": "Vintage Eiffel Tower",
        "fr": "Vintage Eiffel Tower"
      },
      "collectionId": "Paris~2024"
    },
    {
      "filename": "Eiffel_Tower_at_night-Tour_Eiffel_dans_la_nuit.jpg",
      "src": "assets/collections/Paris~2024/Eiffel_Tower/Eiffel_Tower_at_night-Tour_Eiffel_dans_la_nuit.jpg",
      "label": {
        "en": "Eiffel Tower at night",
        "fr": "Tour Eiffel dans la nuit"
      },
      "collectionId": "Paris~2024"
    },
    {
      "filename": "Mountainous_landscape_4-Paysage_montagneux_4.jpg",
      "src": "assets/collections/Saint_Lary~2025/Mountainous_landscape_4-Paysage_montagneux_4.jpg",
      "label": {
        "en": "Mountainous landscape 4",
        "fr": "Paysage montagneux 4"
      },
      "collectionId": "Saint_Lary~2025"
    },
    {
      "filename": "Red_flowers-Fleurs_rouges.jpg",
      "src": "assets/collections/Barèges~2025/Red_flowers-Fleurs_rouges.jpg",
      "label": {
        "en": "Red flowers",
        "fr": "Fleurs rouges"
      },
      "collectionId": "Barèges~2025"
    },
    {
      "filename": "Sea_Turtle-Tortue_de_mer.jpg",
      "src": "assets/collections/Biarritz~2025/Aquarium/Sea_Turtle-Tortue_de_mer.jpg",
      "label": {
        "en": "Sea Turtle",
        "fr": "Tortue de mer"
      },
      "collectionId": "Biarritz~2025"
    },
    {
      "filename": "Southern_Bucorve-Bucorve_du_sud.jpg",
      "src": "assets/collections/Asson_Zoo-Zoo_d'Asson~2024/Animals-Animaux/Southern_Bucorve-Bucorve_du_sud.jpg",
      "label": {
        "en": "Southern Bucorve",
        "fr": "Bucorve du sud"
      },
      "collectionId": "Asson_Zoo-Zoo_d'Asson~2024"
    },
    {
      "filename": "Beluga.jpg",
      "src": "assets/collections/Airplanes-Avions~2025/Beluga.jpg",
      "label": {
        "en": "Beluga",
        "fr": "Beluga"
      },
      "collectionId": "Airplanes-Avions~2025"
    },
    {
      "filename": "Sheep-Mouton.jpg",
      "src": "assets/collections/Barèges~2025/Sheep-Mouton.jpg",
      "label": {
        "en": "Sheep",
        "fr": "Mouton"
      },
      "collectionId": "Barèges~2025"
    },
    {
      "filename": "Serval.jpg",
      "src": "assets/collections/Asson_Zoo-Zoo_d'Asson~2024/Animals-Animaux/Serval.jpg",
      "label": {
        "en": "Serval",
        "fr": "Serval"
      },
      "collectionId": "Asson_Zoo-Zoo_d'Asson~2024"
    },
    {
      "filename": "Parking_lot_covered_in_snow-Parking_enneigé.jpg",
      "src": "assets/collections/Saint_Lary~2025/Parking_lot_covered_in_snow-Parking_enneigé.jpg",
      "label": {
        "en": "Parking lot covered in snow",
        "fr": "Parking enneigé"
      },
      "collectionId": "Saint_Lary~2025"
    },
    {
      "filename": "Mountainous_landscape_2-Paysage_montagneux_2.jpg",
      "src": "assets/collections/Saint_Lary~2025/Mountainous_landscape_2-Paysage_montagneux_2.jpg",
      "label": {
        "en": "Mountainous landscape 2",
        "fr": "Paysage montagneux 2"
      },
      "collectionId": "Saint_Lary~2025"
    },
    {
      "filename": "Stairs_of_Gaztelugatxe-Escaliers_de_Gaztelugatxe.jpg",
      "src": "assets/collections/Spain-Espagne~2025/San Juan de Gaztelugatxe/Stairs_of_Gaztelugatxe-Escaliers_de_Gaztelugatxe.jpg",
      "label": {
        "en": "Stairs of Gaztelugatxe",
        "fr": "Escaliers de Gaztelugatxe"
      },
      "collectionId": "Spain-Espagne~2025"
    }
  ]
};
