// ============================================================
// shared.js — Utilities used across all pages
// ============================================================

// ── MANIFEST LOADER ───────────────────────────────────────
// Fetches assets/manifest.json (generated by generate-manifest.js)
window._manifestCache = null;

async function loadManifest() {
  if (window._manifestCache) return window._manifestCache;
  try {
    const res = await fetch('assets/manifest.json');
    if (!res.ok) throw new Error('manifest not found');
    window._manifestCache = await res.json();
    return window._manifestCache;
  } catch (e) {
    console.warn('Could not load manifest.json. Run: node generate-manifest.js');
    return { collections: [], homeFeed: [] };
  }
}

// ── HEADER ────────────────────────────────────────────────
function renderHeader(activePage) {
  const header = document.getElementById('site-header');
  if (!header) return;
  const { name } = window.SITE_CONFIG;

  const pages = [
    { label: 'Home', href: 'index.html', key: 'home' },
    { label: 'Collections', href: 'collections.html', key: 'collections' },
    { label: 'About', href: 'about.html', key: 'about' },
  ];

  header.innerHTML = `
    <a class="site-logo" href="index.html">${name}</a>
    <nav>
      <ul class="site-nav">
        ${pages.map(p => `
          <li><a href="${p.href}" class="${p.key === activePage ? 'active' : ''}">${p.label}</a></li>
        `).join('')}
      </ul>
    </nav>
  `;
}

// ── FOOTER ────────────────────────────────────────────────
function renderFooter() {
  const footer = document.getElementById('site-footer');
  if (!footer) return;
  const { name, socials } = window.SITE_CONFIG;

  footer.innerHTML = `
    <span>© ${new Date().getFullYear()} ${name}</span>
    <div class="socials">
      ${socials.map(s =>
    `<a href="${s.url}" target="_blank" rel="noopener noreferrer">${s.label}</a>`
  ).join('')}
    </div>
  `;
}

// ── LIGHTBOX ──────────────────────────────────────────────
(function initLightbox() {
  // Inject lightbox HTML once DOM is ready
  function inject() {
    if (document.getElementById('lightbox')) return;
    const el = document.createElement('div');
    el.id = 'lightbox';
    el.innerHTML = `
      <button id="lightbox-close" aria-label="Close lightbox">×</button>
      <img id="lightbox-img" src="" alt="">
      <p id="lightbox-caption"></p>
      <button id="lightbox-action" style="display:none"></button>
    `;
    document.body.appendChild(el);

    document.getElementById('lightbox-close').addEventListener('click', closeLightbox);
    el.addEventListener('click', e => { if (e.target === el) closeLightbox(); });
    document.addEventListener('keydown', e => { if (e.key === 'Escape') closeLightbox(); });
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', inject);
  } else {
    inject();
  }
})();

function openLightbox(src, caption, actionLabel, actionHref) {
  const lb = document.getElementById('lightbox');
  const img = document.getElementById('lightbox-img');
  const cap = document.getElementById('lightbox-caption');
  const action = document.getElementById('lightbox-action');
  if (!lb) return;

  img.src = src;
  img.alt = caption || '';

  if (caption) {
    cap.textContent = caption;
    cap.style.display = 'block';
  } else {
    cap.style.display = 'none';
  }

  if (actionLabel && actionHref) {
    action.style.display = 'inline-block';
    action.textContent = actionLabel;
    action.onclick = () => {
      closeLightbox();
      window.location.href = actionHref;
    };
  } else {
    action.style.display = 'none';
  }

  lb.classList.add('open');
  document.body.style.overflow = 'hidden';
}

function closeLightbox() {
  const lb = document.getElementById('lightbox');
  if (!lb) return;
  lb.classList.remove('open');
  document.body.style.overflow = '';
  document.getElementById('lightbox-img').src = '';
}

// ── HELPERS ───────────────────────────────────────────────

// Convert filename → readable label: "Visit_to_the_Sagrada_Familia.png" → "Visit to the Sagrada Familia"
function fileToLabel(filename) {
  return filename
    .replace(/\.[^.]+$/, '')       // remove extension
    .replace(/[_-]/g, ' ')         // underscores/dashes → spaces
    .replace(/\b\w/g, c => c.toUpperCase()); // Not required but looks nice
}

// Fisher-Yates shuffle
function shuffle(arr) {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

// Get URL query parameter
function getParam(name) {
  return new URLSearchParams(window.location.search).get(name);
}

// Detect portrait vs landscape from image (async)
function getImageOrientation(src) {
  return new Promise(resolve => {
    const img = new Image();
    img.onload = () => resolve(img.naturalWidth <= img.naturalHeight ? 'portrait' : 'landscape');
    img.onerror = () => resolve('landscape');
    img.src = src;
  });
}
